global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'services'
    static_configs:
      - targets:
        - 'feed-svc:8080'
        - 'like-svc:8086'

  - job_name: 'linux_params'
    static_configs:
      - targets:
        - 'cadvisor:8080'