feedService:
  image: akalashnikova7/fanout-feed:latest
  imagePullPolicy: Always
  port: 8080
  config:
    runAddress: ":8080"
    databaseUri: "postgres://postgres@db-feed:5432/feed?sslmode=disable"
    likeServiceUrl: "http://like-svc:8086"
    migrationsPath: "file://migrations"
  probes:
    readinessInitialDelaySeconds: 10
    readinessPeriodSeconds: 5
    livenessInitialDelaySeconds: 20
    livenessPeriodSeconds: 10

likeService:
  image: akalashnikova7/fanout-like:latest
  imagePullPolicy: Always
  port: 8086
  config:
    runAddress: ":8086"
    databaseUri: "postgres://postgres@db-like:5432/like?sslmode=disable"
    migrationsPath: "file://migrations"
  probes:
    readinessInitialDelaySeconds: 10
    readinessPeriodSeconds: 5
    livenessInitialDelaySeconds: 20
    livenessPeriodSeconds: 10

postgres:
  image: postgres:15-alpine
  user: postgres
  secretName: fanout-postgres-credentials
  passwordKey: password
  storageClassName: ""
  feedDb:
    name: feed
    storage: 2Gi
  likeDb:
    name: like
    storage: 2Gi

ollama:
  enabled: true
  image: ollama/ollama:latest
  port: 11434
  model: gemma4:e4b

observability:
  serviceMonitor:
    enabled: true
    namespace: monitoring
    releaseLabel: kube-prom-stack
    interval: 15s

artifactRepository:
  enabled: true
  useDefaultConfigMap: true
  configMapName: artifact-repositories
  configKey: default-v1
  secretName: argo-artifacts-credentials
  s3:
    bucket: argo-workflows
    endpoint: argo-artifacts.fanout.svc.cluster.local:9000
    insecure: true
    accessKeyKey: accessKey
    secretKeyKey: secretKey
  minio:
    enabled: true
    serviceName: argo-artifacts
    image: minio/minio:latest
    imagePullPolicy: IfNotPresent
    bucketInit:
      image: minio/mc:latest
      imagePullPolicy: IfNotPresent
    dataPath: /data
    storage:
      enabled: true
      size: 5Gi
    service:
      apiPort: 9000
      consolePort: 9001

workflow:
  enabled: true
  metricsPvc:
    storage: 200Mi
  serviceAccount:
    name: argo-workflow
  template:
    name: fanout-perftest-pipeline
  assistantImage:
    image: akalashnikova7/k6:latest
    pullPolicy: Always
  fillImage: curlimages/curl:8.7.1
  kubectlImage: bitnami/kubectl:latest
  baselineImages:
    feed: akalashnikova7/fanout-feed:latest
    like: akalashnikova7/fanout-like:latest
  candidateImages:
    feed: akalashnikova7/fanout-feed:test
    like: akalashnikova7/fanout-like:test
  serviceUrl: http://feed-svc:8080
  prometheusUrl: http://kube-prom-stack-kube-prome-prometheus.monitoring.svc:9090
  ollamaUrl: http://ollama:11434
  duration: 2m
  promqlQueriesFile: /config/queries.txt
  k6ScriptFile: /config-k6/load_k6_feed.js
  comparisonPromptFile: /config-prompts/comparison-prompt.txt
  runAnalysisPromptFile: /config-prompts/run-analysis-prompt.txt
  htmlTemplateFile: /config-html/template.html
  runAnalysis:
    enabled: true
  seedData:
    enabled: false
    numUsers: 16
    postsPerUser: 16
