apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fanout
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alexandragenk/fanout.git
    targetRevision: test
    path: helm-charts/fanout
  destination:
    server: https://kubernetes.default.svc
    namespace: fanout
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
