apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fanout
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: fanout
            namespace: fanout
            path: helm-charts/fanout
            targetRevision: master
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/alexandragenk/fanout.git
        targetRevision: '{{targetRevision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
