apiVersion: v1
kind: ConfigMap
metadata:
  name: feed-config
  namespace: {{ include "fanout.namespace" . }}
data:
  config.yaml: |
    run_address: {{ .Values.feedService.config.runAddress | quote }}
    database_uri: {{ .Values.feedService.config.databaseUri | quote }}
    like_service_url: {{ .Values.feedService.config.likeServiceUrl | quote }}
    migrations_path: {{ .Values.feedService.config.migrationsPath | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: like-config
  namespace: {{ include "fanout.namespace" . }}
data:
  config.yaml: |
    run_address: {{ .Values.likeService.config.runAddress | quote }}
    database_uri: {{ .Values.likeService.config.databaseUri | quote }}
    migrations_path: {{ .Values.likeService.config.migrationsPath | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promql-queries-config
  namespace: {{ include "fanout.namespace" . }}
data:
  queries.txt: |
{{ .Values.promqlQueries | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-scripts-config
  namespace: {{ include "fanout.namespace" . }}
data:
  load_k6_feed.js: |
{{ .Values.k6Script | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: llm-prompts-config
  namespace: {{ include "fanout.namespace" . }}
data:
  comparison-prompt.txt: |
{{ .Values.comparisonPrompt | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-template-config
  namespace: {{ include "fanout.namespace" . }}
data:
  template.html: |
{{ .Files.Get "files/report-template.html" | indent 4 }}
