{{- $serviceMonitor := .Values.observability.serviceMonitor -}}
{{- if $serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: feed
  namespace: {{ $serviceMonitor.namespace }}
  labels:
    release: {{ $serviceMonitor.releaseLabel }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: feed
  endpoints:
    - port: http
      path: /metrics
      interval: {{ $serviceMonitor.interval }}
  targetLabels:
    - app
  podTargetLabels:
    - metrics_group
    - app.kubernetes.io/name
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: like
  namespace: {{ $serviceMonitor.namespace }}
  labels:
    release: {{ $serviceMonitor.releaseLabel }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: like
  endpoints:
    - port: http
      path: /metrics
      interval: {{ $serviceMonitor.interval }}
  targetLabels:
    - app
  podTargetLabels:
    - metrics_group
    - app.kubernetes.io/name
{{- end }}
